name: Test Tag and Release
on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  Craete_Tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  Release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v') && github.ref != 'refs/tags/v'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create Zip Archive
        run: zip -r release-package.zip . -x'.github*' -x'*node_modules*' -x'*.git*' -x '.*' -x '*.zip' -x "*/.*"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-package.zip
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}