name: Test Secret System
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        run: echo "${{ secrets.TEXT }}" >> secret.txt
      - name: Display Secret File
        run: cat secret.txt
